const recipes = [
  {
    name: 'Vanilla',
    subtitle: 'Simple and elegant',
    description:
      'Vanilla is one of the most complex spices in the world, yet few things are as paradoxically simple as a classic Vanilla ice cream. Smooth, creamy, and delicious - it will never get old!',
    estimatedMass: 945,
    base: 'Vanilla',
    instructions: [
      'Measure out and mix together all of the solids.',
      'Add the dairy to a medium-sized, heavy-bottomed pot.',
      'Heat the dairy on the stove until warm, around 90° F.',
      'Slowly add the solids to the pot, whisking as your pour to dissolve the solids. Continue whisking until dissolved.',
      'Prepare an ice bath by nesting a metal mixing bowl into a larger bowl that is filled with ice and water.',
      'Continue cooking the dairy, whisking occasionally. Cook until the temperature reaches 165° F.',
      'Once the mixture is at temperature, pour through a fine mesh strainer into the bowl in the ice bath.',
      'Whisk occasionally while the mixture cools. Once the temperature is below 80° F, add the finishing ingredients.',
      'Cover the bowl or transfer the mixture to a container. Store in the fridge to age, at least 4 hours and up to overnight.',
      "Churn in an ice cream machine according to the manufacture's instructions, about 15-20 minutes.",
      'Draw ice cream from the machine and into a freezer-safe container. Store in the freezer.',
    ],
    ingredients: [
      {
        name: 'Whole Milk',
        quantity: 470,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Heavy Cream',
        quantity: 341,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Sugar',
        quantity: 63,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Dextrose',
        quantity: 57,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Milk Powder',
        quantity: 60,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Stabilizer Blend',
        quantity: 1.5,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Locust bean gum',
              quantity: 8,
              unit: 'g',
            },
            {
              name: 'Guar gum',
              quantity: 4,
              unit: 'g',
            },
            {
              name: 'Lambda carageenan',
              quantity: 2,
              unit: 'g',
            },
          ],
          instructions: [
            'Mix together until thoroughly combined.',
            'Store in a sealed container or plastic bag at room temperature.',
          ],
          description:
            'My go-to stabilizer blend, taken from the UnderBelly blog. Makes enough for ~10 batches of ice cream. Can likely be replaced by most commercial stabilizer blends.',
        },
        category: 'solids',
      },
      {
        name: 'Salt',
        quantity: 1.5,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Vanilla Extract',
        quantity: 6,
        unit: 'g',
        category: 'finishing',
      },
    ],
    id: '01952f70-5e37-7527-8baf-98d987a1f0fa',
    nameKey: 'vanilla',
    version: 1,
    analysis: {
      totalFat: 139.67999999999998,
      milkFat: 139.67999999999998,
      totalSolids: 383.13599999999997,
      totalSolidsNonfat: 243.45600000000002,
      milkSolidsNonfat: 120.456,
      water: 611.2459999999999,
      sugars: 120,
      totalMass: 1000,
      pod: 113.8695,
      pac: 232.035,
      stabilizers: 1.5,
    },
  },
  {
    name: 'Chocolate',
    subtitle: 'Rich and bold',
    description:
      'Few flavors are as prized and beloved as chocolate, made from beans of the cacao plant. This recipe is for a daily driver type of chocolate ice cream. It always hits the spot!',
    estimatedMass: 937,
    base: 'Chocolate',
    instructions: [
      'Measure out and mix together all of the solids.',
      'Add the dairy to a medium-sized, heavy-bottomed pot.',
      'Heat the dairy on the stove until warm, around 90° F.',
      'Slowly add the solids to the pot, whisking as your pour to dissolve the solids. Continue whisking until dissolved. If not all the cocoa dissolves right away, that is okay. Keep going.',
      'Prepare an ice bath by nesting a metal mixing bowl into a larger bowl that is filled with ice and water.',
      'Continue cooking the dairy, whisking occasionally. Cook until the temperature reaches 165° F.',
      'Once the mixture is at temperature, pour through a fine mesh strainer into the bowl in the ice bath.',
      'Whisk occasionally while the mixture cools. Once the temperature is below 80° F, add the finishing ingredients.',
      'Cover the bowl or transfer the mixture to a container. Store in the fridge to age, at least 4 hours and up to overnight.',
      "Churn in an ice cream machine according to the manufacture's instructions, about 15-20 minutes.",
      'Draw ice cream from the machine and into a freezer-safe container. Store in the freezer.',
    ],
    ingredients: [
      {
        name: 'Whole Milk',
        quantity: 514,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Heavy Cream',
        quantity: 291,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Sugar',
        quantity: 29,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Dextrose',
        quantity: 64,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Fructose',
        quantity: 26,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Milk Powder',
        quantity: 40,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Cocoa Powder',
        quantity: 30,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Stabilizer Blend',
        quantity: 1.5,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Locust bean gum',
              quantity: 8,
              unit: 'g',
            },
            {
              name: 'Guar gum',
              quantity: 4,
              unit: 'g',
            },
            {
              name: 'Lambda carageenan',
              quantity: 2,
              unit: 'g',
            },
          ],
          instructions: [
            'Mix together until thoroughly combined.',
            'Store in a sealed container or plastic bag at room temperature.',
          ],
          description:
            'My go-to stabilizer blend, taken from the UnderBelly blog. Makes enough for ~10 batches of ice cream. Can likely be replaced by most commercial stabilizer blends.',
        },
        category: 'solids',
      },
      {
        name: 'Salt',
        quantity: 1.5,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Vanilla Extract',
        quantity: 3,
        unit: 'g',
        category: 'finishing',
      },
    ],
    id: '01952f70-5e38-75ee-bfed-54a78a02ddbf',
    nameKey: 'chocolate',
    version: 1,
    analysis: {
      totalFat: 129.68399999999997,
      milkFat: 123.26399999999998,
      totalSolids: 376.792,
      totalSolidsNonfat: 247.108,
      milkSolidsNonfat: 101.52799999999999,
      water: 619.0799999999999,
      sugars: 119,
      totalMass: 1000,
      pod: 112.9893,
      pac: 238.145,
      stabilizers: 1.5,
    },
  },
  {
    name: 'Butter Pecan',
    subtitle: 'Candied pecans mixed into brown butter and molasses ice cream',
    description:
      'This is a decadent, buttery ice cream filled with salty-sweet pecans that is a far cry from a standard vanilla with some pecans thrown in!',
    estimatedMass: 935,
    base: 'Butter Pecan',
    instructions: [
      'Measure out and mix together all of the solids.',
      'Add the dairy to a medium-sized, heavy-bottomed pot.',
      'Heat the dairy on the stove until warm, around 90° F.',
      'Slowly add the solids to the pot, whisking as your pour to dissolve the solids. Continue whisking until dissolved. If not all the toasted milk powder dissolves right away, that is okay. Keep going.',
      'Prepare an ice bath by nesting a metal mixing bowl into a larger bowl that is filled with ice and water.',
      'Temper the egg yolks by whisking them in a bowl, then whisking in about a half cup of warm dairy a little bit at a time.',
      'Add the egg mixture back to the pot, scraping the sides with a rubber spatula.',
      'Continue cooking the mixture, whisking frequently to prevent scrambling the eggs. Cook until the temperature reaches 165° F.',
      'Once the mixture is at temperature, pour through a fine mesh strainer into the bowl in the ice bath.',
      'Whisk occasionally while the mixture cools. Once the temperature is below 80° F, add the finishing ingredients.',
      'Measure the final weight of the mixture and transfer into a container. Use the final weight to determine the amount of pecans to mix in while churning.',
      'Store in the fridge to age, at least 4 hours and up to overnight.',
      "Churn in an ice cream machine according to the manufacture's instructions, about 15-20 minutes.",
      'Once the ice cream is nearly done churning, slowly add the pecans to the churner so that they disperse through the ice cream.',
      'Draw ice cream from the machine and into a freezer-safe container. Store in the freezer.',
    ],
    ingredients: [
      {
        name: 'Whole Milk',
        quantity: 465,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Heavy Cream',
        quantity: 333,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Sugar',
        quantity: 27,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Brown Sugar',
        quantity: 35,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Dextrose',
        quantity: 58,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Milk Powder',
        quantity: 35,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Toasted Milk Powder',
        quantity: 25,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Milk Powder',
              quantity: 50,
              unit: 'g',
            },
          ],
          instructions: [
            'Preheat the oven to 300° F.',
            'Spread out milk powder on sheet pan lined with parchment paper or aluminum foil.',
            'Toast in oven for 12 minutes, pulling out to stir halfway through.',
            'Remove and remove the paper/foil from the pan and place somewhere to cool down.',
            'Store in a sealed container in a cool, dry place. It should keep fairly well.',
          ],
          description:
            'Toasting milk solids is exactly what happens when you brown butter. This replicates those flavors, without the milkfat.',
        },
        category: 'solids',
      },
      {
        name: 'Egg Yolks',
        quantity: 15,
        unit: 'g',
        category: 'other',
      },
      {
        name: 'Stabilizer Blend',
        quantity: 1.5,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Locust bean gum',
              quantity: 8,
              unit: 'g',
            },
            {
              name: 'Guar gum',
              quantity: 4,
              unit: 'g',
            },
            {
              name: 'Lambda carageenan',
              quantity: 2,
              unit: 'g',
            },
          ],
          instructions: [
            'Mix together until thoroughly combined.',
            'Store in a sealed container or plastic bag at room temperature.',
          ],
          description:
            'My go-to stabilizer blend, taken from the UnderBelly blog. Makes enough for ~10 batches of ice cream. Can likely be replaced by most commercial stabilizer blends.',
        },
        category: 'solids',
      },
      {
        name: 'Salt',
        quantity: 1.5,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Vanilla Extract',
        quantity: 4,
        unit: 'g',
        category: 'finishing',
      },
      {
        name: 'Candied Pecans',
        quantity: 9,
        unit: '% of final weight',
        preparation: {
          ingredients: [
            {
              name: 'Chopped pecans',
              quantity: 100,
              unit: 'g',
            },
            {
              name: 'Unsalted butter',
              quantity: 20,
              unit: 'g',
            },
            {
              name: 'Brown Sugar',
              quantity: 20,
              unit: 'g',
            },
            {
              name: 'Water',
              quantity: 20,
              unit: 'g',
            },
            {
              name: 'Salt',
              quantity: 2,
              unit: 'g',
            },
          ],
          instructions: [
            'Add sugar, water, and butter to large saucepan.',
            'Cook on medium-low and stir to melt the butter and dissolve the sugar.',
            'Once the mixture is just starting to bubble, add the chopped pecans and salt and stir to coat the nuts in the mixture.',
            "Cook until the pecans become fragrant. It should just take a minute or two. Don't overcook them - if they smell good, they're done.",
            'Transfer to a plate to cool, then transfer to a sealed container.',
            'Store in the fridge.',
          ],
          description:
            'Butter and pecans are a match made in heaven. Sugar and salt help the flavor to pop once frozen in ice cream. Toasting brings out the flavor of the nuts but be careful not to overcook them!',
        },
        category: 'churning',
      },
    ],
    id: '01952f70-5e38-75ee-bfed-590389b7ee3c',
    nameKey: 'butter-pecan',
    version: 1,
    analysis: {
      totalFat: 140.07,
      milkFat: 136.62,
      totalSolids: 386.688,
      totalSolidsNonfat: 246.618,
      milkSolidsNonfat: 119.568,
      water: 608.6890000000001,
      sugars: 120,
      totalMass: 1000,
      pod: 124.082,
      pac: 221.95499999999998,
      stabilizers: 1.5,
    },
  },
  {
    name: 'Cookies and Cream',
    subtitle: 'Genuine, name-brand Oreo cookies mixed into vanilla ice cream',
    description:
      'Cookies paired with cream is among the greatest duos known to mankind. It will never not hit.',
    estimatedMass: 950,
    base: 'Vanilla',
    instructions: [
      'Measure out and mix together all of the solids.',
      'Add the dairy to a medium-sized, heavy-bottomed pot.',
      'Heat the dairy on the stove until warm, around 90° F.',
      'Slowly add the solids to the pot, whisking as your pour to dissolve the solids. Continue whisking until dissolved.',
      'Prepare an ice bath by nesting a metal mixing bowl into a larger bowl that is filled with ice and water.',
      'Continue cooking the dairy, whisking occasionally. Cook until the temperature reaches 165° F.',
      'Once the mixture is at temperature, pour through a fine mesh strainer into the bowl in the ice bath.',
      'Whisk occasionally while the mixture cools. Once the temperature is below 80° F, add the finishing ingredients.',
      "Measure the final weight of the mixture and transfer into a container. Use the final weight to determine the amount of Oreo's to mix in while churning.",
      'Store in the fridge to age, at least 4 hours and up to overnight.',
      "Churn in an ice cream machine according to the manufacture's instructions, about 15-20 minutes.",
      "Once the ice cream is nearly done churning, slowly add the crushed Oreo's to the churner so that they disperse through the ice cream.",
      'Draw ice cream from the machine and into a freezer-safe container. Store in the freezer.',
    ],
    ingredients: [
      {
        name: 'Whole Milk',
        quantity: 454,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Heavy Cream',
        quantity: 360,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Sugar',
        quantity: 62,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Dextrose',
        quantity: 56,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Milk Powder',
        quantity: 60,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Stabilizer Blend',
        quantity: 1.5,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Locust bean gum',
              quantity: 8,
              unit: 'g',
            },
            {
              name: 'Guar gum',
              quantity: 4,
              unit: 'g',
            },
            {
              name: 'Lambda carageenan',
              quantity: 2,
              unit: 'g',
            },
          ],
          instructions: [
            'Mix together until thoroughly combined.',
            'Store in a sealed container or plastic bag at room temperature.',
          ],
          description:
            'My go-to stabilizer blend, taken from the UnderBelly blog. Makes enough for ~10 batches of ice cream. Can likely be replaced by most commercial stabilizer blends.',
        },
        category: 'solids',
      },
      {
        name: 'Salt',
        quantity: 1.5,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Vanilla Extract',
        quantity: 5,
        unit: 'g',
        category: 'finishing',
      },
      {
        name: "Crushed Oreo's",
        quantity: 15,
        unit: '% of final weight',
        preparation: {
          ingredients: [
            {
              name: 'Oreo Cookies',
              quantity: 15,
            },
          ],
          instructions: [
            'Separate the cookies from the icing by twisting, pulling apart, and scraping off any residual icing with a knife.',
            'Discard icing and weigh cookies. 15 is an approximation - use as many as you need for the given ice cream recipe.',
            'Transfer the cookies to a sealed bag. Crush with a kitchen mallet until desired consistency is reached. I like a mix of powder and chunks.',
            'Keep sealed and stored until ready to use.',
          ],
          description:
            'I think ice cream is better with only the cookies, so I recommend removing the icing. That said, if you want it - keep it! Note that the amount is just an estimate - use as much as you need for your batch.',
        },
        category: 'churning',
      },
    ],
    id: '01952f70-5e39-718c-8736-5a49cfb64861',
    nameKey: 'cookies-and-cream',
    version: 1,
    analysis: {
      totalFat: 145.944,
      milkFat: 145.944,
      totalSolids: 387.056,
      totalSolidsNonfat: 241.112,
      milkSolidsNonfat: 120.112,
      water: 607.7719999999999,
      sugars: 118,
      totalMass: 1000,
      pod: 112.0218,
      pac: 229.16,
      stabilizers: 1.5,
    },
  },
  {
    name: 'Mint Chocolate Chip',
    subtitle:
      'Cool peppermint ice cream, riddled with flecks of dark chocolate',
    description:
      'A true classic! Refreshing and invigorating at the same time. The ice cream will be white by default but you can add ~5 drops of green food coloring for an old-school appearance.',
    estimatedMass: 950,
    base: 'Mint',
    instructions: [
      'Measure out and mix together all of the solids.',
      'Add the dairy to a medium-sized, heavy-bottomed pot.',
      'Heat the dairy on the stove until warm, around 90° F.',
      'Slowly add the solids to the pot, whisking as your pour to dissolve the solids. Continue whisking until dissolved.',
      'Prepare an ice bath by nesting a metal mixing bowl into a larger bowl that is filled with ice and water.',
      'Continue cooking the dairy, whisking occasionally. Cook until the temperature reaches 165° F.',
      'Once the mixture is at temperature, pour through a fine mesh strainer into the bowl in the ice bath.',
      'Whisk occasionally while the mixture cools. Once the temperature is below 80° F, add the finishing ingredients.',
      'Measure the final weight of the mixture and transfer into a container. Use the final weight to calculate the amount of chocolate to mix in while churning.',
      'Store in the fridge to age, at least 4 hours and up to overnight.',
      "Churn in an ice cream machine according to the manufacture's instructions, about 15-20 minutes.",
      'Once the ice cream is a few minutes away from being done churning, slowly drizzle the melted chocolate mixture into the churner. It will break up as it freezes, resulting in scattered flecks being dispersed throughout the ice cream.',
      'Draw ice cream from the machine and into a freezer-safe container. Store in the freezer.',
    ],
    ingredients: [
      {
        name: 'Whole Milk',
        quantity: 467,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Heavy Cream',
        quantity: 343,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Sugar',
        quantity: 65,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Dextrose',
        quantity: 55,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Milk Powder',
        quantity: 60,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Stabilizer Blend',
        quantity: 1.5,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Locust bean gum',
              quantity: 8,
              unit: 'g',
            },
            {
              name: 'Guar gum',
              quantity: 4,
              unit: 'g',
            },
            {
              name: 'Lambda carageenan',
              quantity: 2,
              unit: 'g',
            },
          ],
          instructions: [
            'Mix together until thoroughly combined.',
            'Store in a sealed container or plastic bag at room temperature.',
          ],
          description:
            'My go-to stabilizer blend, taken from the UnderBelly blog. Makes enough for ~10 batches of ice cream. Can likely be replaced by most commercial stabilizer blends.',
        },
        category: 'solids',
      },
      {
        name: 'Salt',
        quantity: 1.5,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Peppermint Extract',
        quantity: 7,
        unit: 'g',
        category: 'finishing',
      },
      {
        name: 'Chocolate Chips',
        quantity: 7,
        unit: '% of final weight',
        preparation: {
          ingredients: [
            {
              name: 'Dark Chocolate',
              quantity: 80,
              unit: '%',
            },
            {
              name: 'Refined Coconut Oil',
              quantity: 20,
              unit: '%',
            },
          ],
          instructions: [
            'Calculate and measure, in weight, the amounts of chocolate and coconut oil based on the provided ratios and the ice cream recipe.',
            'Fill a large pot of water with just a couple inches of water.',
            'Heat the water on the stove until boiling.',
            'Add the chocolate and coconut oil to a metal mixing bowl or double boiler.',
            'Turn off the stove and nest the bowl in the pot - the bottom should not touch the water.',
            'As the steam melts the chocolate and the oil, stir occasionally with a heatproof spatula.',
            'Once the mixture is totally melted and well-integrated, remove from heat.',
            "When pouring into the ice cream, I like the temperature to be between 110-130° F, though that isn't a strict range.",
          ],
          description:
            'Mixing chocolate with coconut oil prevents the chocolate from freezing too hard. Pouring the mixture in warm will result in the chips being broken up as they freeze. A cooler mixture will result in larger chips; hotter, smaller.',
        },
        category: 'churning',
      },
    ],
    id: '01952f70-5e39-718c-8736-5c0e021d2de3',
    nameKey: 'mint-chocolate-chip',
    version: 1,
    analysis: {
      totalFat: 140.29199999999997,
      milkFat: 140.29199999999997,
      totalSolids: 383.596,
      totalSolidsNonfat: 243.304,
      milkSolidsNonfat: 120.304,
      water: 610.313,
      sugars: 120,
      totalMass: 1000,
      pod: 114.3504,
      pac: 230.185,
      stabilizers: 1.5,
    },
  },
  {
    name: 'Pistachio',
    subtitle: 'Pistachio flavored ice cream mixed with more pistachios',
    description:
      'For whatever reason, the flavor of this nut just works so well in ice cream. No almond extract here, only pure pistachio pizzazz.',
    estimatedMass: 945,
    base: 'Pistachio',
    instructions: [
      'Measure out and mix together all of the solids.',
      'Add the dairy to a medium-sized, heavy-bottomed pot.',
      'Heat the dairy on the stove until warm, around 90° F.',
      'Slowly add the solids to the pot, whisking as your pour to dissolve the solids. Continue whisking until dissolved.',
      'Prepare an ice bath by nesting a metal mixing bowl into a larger bowl that is filled with ice and water.',
      'Continue cooking the dairy, whisking occasionally. Cook until the temperature reaches 165° F.',
      'Once the mixture is at temperature, pour through a fine mesh strainer into the bowl in the ice bath.',
      'Whisk occasionally while the mixture cools to below 80° F.',
      'Measure the final weight of the mixture and transfer into a container. Use the final weight to calculate the amount of pistachios to mix in while churning.',
      'Store in the fridge to age, at least 4 hours and up to overnight.',
      "Churn in an ice cream machine according to the manufacture's instructions, about 15-20 minutes.",
      'Once the ice cream is nearly done churning, slowly add the pistachios to the churner so that they disperse through the ice cream.',
      'Draw ice cream from the machine and into a freezer-safe container. Store in the freezer.',
    ],
    ingredients: [
      {
        name: 'Pistachio Infused Milk',
        quantity: 360,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Whole Milk',
              quantity: 443,
              unit: 'g',
            },
            {
              name: 'Unsalted Pistachios',
              quantity: 111,
              unit: 'g',
            },
          ],
          instructions: [
            'Preheat oven to 300° F.',
            'Arrange pistachios on a sheet pan lined with parchment paper or aluminum foil.',
            'Toast nuts for 5 minutes or until fragrant. Be careful not to overcook them.',
            'Add nuts and milk to a blender. Quickly pulse blender 3-4 times. The nuts should not be completely pulverized or they will be hard to strain.',
            'Leave in the fridge to steep for 8-24 hours. Shake every now and then if you think about it.',
            'Strain through a nut milk bag. Squeeze the bag to extract as much yield as you can. You should end up with 388+ g of infused milk if you try hard and believe in yourself.',
            'Store in a sealed container in the fridge until ready to use.',
          ],
          description:
            "This is the best method I've found for flavoring an ice cream with pistachios without compromising on texture. Allocate the time needed for a good long steep and you'll be rewarded with a flavorful ice cream.",
        },
        category: 'dairy',
      },
      {
        name: 'Whole Milk',
        quantity: 127,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Heavy Cream',
        quantity: 330,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Sugar',
        quantity: 65,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Dextrose',
        quantity: 55,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Milk Powder',
        quantity: 60,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Stabilizer Blend',
        quantity: 1.5,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Locust bean gum',
              quantity: 8,
              unit: 'g',
            },
            {
              name: 'Guar gum',
              quantity: 4,
              unit: 'g',
            },
            {
              name: 'Lambda carageenan',
              quantity: 2,
              unit: 'g',
            },
          ],
          instructions: [
            'Mix together until thoroughly combined.',
            'Store in a sealed container or plastic bag at room temperature.',
          ],
          description:
            'My go-to stabilizer blend, taken from the UnderBelly blog. Makes enough for ~10 batches of ice cream. Can likely be replaced by most commercial stabilizer blends.',
        },
        category: 'solids',
      },
      {
        name: 'Salt',
        quantity: 1.5,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Pistachios',
        quantity: 5,
        unit: '% of final weight',
        category: 'churning',
      },
    ],
    id: '01952f70-5e3a-7769-ba68-4d5db151516d',
    nameKey: 'pistachio',
    version: 1,
    analysis: {
      totalFat: 136.332,
      milkFat: 136.332,
      totalSolids: 380.668,
      totalSolidsNonfat: 244.336,
      milkSolidsNonfat: 121.336,
      water: 616.5509999999999,
      sugars: 120,
      totalMass: 1000,
      pod: 114.47789999999999,
      pac: 230.53,
      stabilizers: 1.5,
    },
  },
  {
    name: 'Banana',
    subtitle: 'Pure banana ice cream',
    description:
      'Bursting with vibrant, tropical banana flavor that comes from steeping ripe bananas in the base, a technique I learned from "Hello My Name Is Ice Cream", by Dana Cree.',
    estimatedMass: 850,
    base: 'Banana',
    instructions: [
      'Measure out and mix together all of the solids.',
      'Add the dairy to a medium-sized, heavy-bottomed pot.',
      'Heat the dairy on the stove until warm, around 90° F.',
      'While the dairy is heating up, peel the ripe bananas and put them in a metal mixing bowl or freezer gallon bag.',
      'Slowly add the solids to the pot, whisking as your pour to dissolve the solids. Continue whisking until dissolved.',
      'Prepare an ice bath by filling a large bowl with ice and water.',
      'Temper the egg yolks by whisking them in a bowl, then whisking in about a half cup of warm dairy a little bit at a time.',
      'Add the egg mixture back to the pot, scraping the sides with a rubber spatula.',
      'Continue cooking the mixture, whisking frequently to prevent scrambling the eggs. Cook until the temperature reaches 165° F.',
      'Once the mixture is at temperature, pour into the bowl or bag containing the bananas.',
      'Nest the bowl or the bag in the ice bath to cool.',
      'Once the temperature is below 80° F, add the finishing ingredients and carefully agitate or stir to combine.',
      'Leaving the bananas in the mixture, place the bowl (covered) or bag in the fridge so the bananas can steep, 12-24 hours.',
      'Pour the mixture through a fine mesh strainer to filter out the bananas and any other undissolved solids.',
      "Churn in an ice cream machine according to the manufacture's instructions, about 15-20 minutes.",
      'Draw ice cream from the machine and into a freezer-safe container. Store in the freezer.',
    ],
    ingredients: [
      {
        name: 'Whole Milk',
        quantity: 465,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Heavy Cream',
        quantity: 333,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Sugar',
        quantity: 64,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Dextrose',
        quantity: 56,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Milk Powder',
        quantity: 60,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Stabilizer Blend',
        quantity: 1.5,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Locust bean gum',
              quantity: 8,
              unit: 'g',
            },
            {
              name: 'Guar gum',
              quantity: 4,
              unit: 'g',
            },
            {
              name: 'Lambda carageenan',
              quantity: 2,
              unit: 'g',
            },
          ],
          instructions: [
            'Mix together until thoroughly combined.',
            'Store in a sealed container or plastic bag at room temperature.',
          ],
          description:
            'My go-to stabilizer blend, taken from the UnderBelly blog. Makes enough for ~10 batches of ice cream. Can likely be replaced by most commercial stabilizer blends.',
        },
        category: 'solids',
      },
      {
        name: 'Salt',
        quantity: 1.5,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Egg Yolks',
        quantity: 16,
        unit: 'g',
        category: 'other',
      },
      {
        name: 'Vanilla Extract',
        quantity: 3,
        unit: 'g',
        category: 'finishing',
      },
      {
        name: 'Bananas',
        quantity: 4,
        category: 'steeping',
      },
    ],
    id: '01952f70-5e3b-762f-b15f-cb5bb57bfa08',
    nameKey: 'banana',
    version: 1,
    analysis: {
      totalFat: 140.3,
      milkFat: 136.62,
      totalSolids: 387.188,
      totalSolidsNonfat: 246.888,
      milkSolidsNonfat: 119.568,
      water: 608.663,
      sugars: 120,
      totalMass: 1000,
      pod: 114.082,
      pac: 230.65499999999997,
      stabilizers: 1.5,
    },
  },
  {
    name: 'Coffee',
    subtitle: 'Pure coffee ice cream, a wake up call',
    description:
      "Rich and smooth, with bold, aromatic coffee that's perfect for any coffee lover. Your favorite brew, now in a scoop!",
    estimatedMass: 940,
    base: 'Coffee',
    instructions: [
      'Measure out and mix together all of the solids.',
      'Add the dairy to a medium-sized, heavy-bottomed pot.',
      'Heat the dairy on the stove until warm, around 90° F.',
      'Slowly add the solids to the pot, whisking as your pour to dissolve the solids. Continue whisking until dissolved. If not all the instant coffee dissolves right away, that is okay. Keep going.',
      'Prepare an ice bath by nesting a metal mixing bowl into a larger bowl that is filled with ice and water.',
      'Temper the egg yolks by whisking them in a bowl, then whisking in about a half cup of warm dairy a little bit at a time.',
      'Add the egg mixture back to the pot, scraping the sides with a rubber spatula.',
      'Continue cooking the mixture, whisking frequently to prevent scrambling the eggs. Cook until the temperature reaches 165° F.',
      'Once the mixture is at temperature, pour through a fine mesh strainer into the bowl in the ice bath.',
      'Whisk occasionally while the mixture cools to below 80° F.',
      'Cover the bowl or transfer the mixture to a container. Store in the fridge to age, at least 4 hours and up to overnight.',
      "Churn in an ice cream machine according to the manufacture's instructions, about 15-20 minutes.",
      'Draw ice cream from the machine and into a freezer-safe container. Store in the freezer.',
    ],
    ingredients: [
      {
        name: 'Whole Milk',
        quantity: 465,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Heavy Cream',
        quantity: 333,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Sugar',
        quantity: 65,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Dextrose',
        quantity: 55,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Milk Powder',
        quantity: 55,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Egg Yolks',
        quantity: 16,
        unit: 'g',
        category: 'other',
      },
      {
        name: 'Stabilizer Blend',
        quantity: 1.5,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Locust bean gum',
              quantity: 8,
              unit: 'g',
            },
            {
              name: 'Guar gum',
              quantity: 4,
              unit: 'g',
            },
            {
              name: 'Lambda carageenan',
              quantity: 2,
              unit: 'g',
            },
          ],
          instructions: [
            'Mix together until thoroughly combined.',
            'Store in a sealed container or plastic bag at room temperature.',
          ],
          description:
            'My go-to stabilizer blend, taken from the UnderBelly blog. Makes enough for ~10 batches of ice cream. Can likely be replaced by most commercial stabilizer blends.',
        },
        category: 'solids',
      },
      {
        name: 'Salt',
        quantity: 1.5,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Instant Coffee',
        quantity: 8,
        unit: 'g',
        category: 'solids',
      },
    ],
    id: '01952f70-5e3b-762f-b15f-ce4a1b328b61',
    nameKey: 'coffee',
    version: 1,
    analysis: {
      totalFat: 140.3,
      milkFat: 136.62,
      totalSolids: 390.188,
      totalSolidsNonfat: 249.888,
      milkSolidsNonfat: 114.568,
      water: 607.085,
      sugars: 120,
      totalMass: 1000,
      pod: 113.932,
      pac: 228.855,
      stabilizers: 1.5,
    },
  },
  {
    name: 'Chocolate Chip Cookie Dough',
    subtitle: 'Fresh vanilla ice cream mixed with bits of real cookie dough',
    description:
      'The perfect combination of creamy vanilla ice cream and soft, chewy cookie dough chunks. It’s a classic treat that never goes out of style!',
    estimatedMass: 935,
    base: 'Vanilla',
    instructions: [
      'Measure out and mix together all of the solids.',
      'Add the dairy to a medium-sized, heavy-bottomed pot.',
      'Heat the dairy on the stove until warm, around 90° F.',
      'Slowly add the solids to the pot, whisking as your pour to dissolve the solids. Continue whisking until dissolved.',
      'Prepare an ice bath by nesting a metal mixing bowl into a larger bowl that is filled with ice and water.',
      'Temper the egg yolks by whisking them in a bowl, then whisking in about a half cup of warm dairy a little bit at a time.',
      'Add the egg mixture back to the pot, scraping the sides with a rubber spatula.',
      'Continue cooking the mixture, whisking frequently to prevent scrambling the eggs. Cook until the temperature reaches 165° F.',
      'Once the mixture is at temperature, pour through a fine mesh strainer into the bowl in the ice bath.',
      'Whisk occasionally while the mixture cools. Once the temperature is below 80° F, add the finishing ingredients.',
      'Measure the final weight of the mixture and transfer into a container. Use the final weight to calculate the amount of cookie dough to mix in while churning.',
      'Store in the fridge to age, at least 4 hours and up to overnight.',
      "Churn in an ice cream machine according to the manufacture's instructions, about 15-20 minutes.",
      'Draw ice cream from the machine and into a freezer-safe container, layering in the cookie dough bits as you go. Store in the freezer.',
    ],
    ingredients: [
      {
        name: 'Whole Milk',
        quantity: 465,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Heavy Cream',
        quantity: 344,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Sugar',
        quantity: 61,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Dextrose',
        quantity: 57,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Milk Powder',
        quantity: 60,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Egg Yolks',
        quantity: 16,
        unit: 'g',
        category: 'other',
      },
      {
        name: 'Stabilizer Blend',
        quantity: 1.5,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Locust bean gum',
              quantity: 8,
              unit: 'g',
            },
            {
              name: 'Guar gum',
              quantity: 4,
              unit: 'g',
            },
            {
              name: 'Lambda carageenan',
              quantity: 2,
              unit: 'g',
            },
          ],
          instructions: [
            'Mix together until thoroughly combined.',
            'Store in a sealed container or plastic bag at room temperature.',
          ],
          description:
            'My go-to stabilizer blend, taken from the UnderBelly blog. Makes enough for ~10 batches of ice cream. Can likely be replaced by most commercial stabilizer blends.',
        },
        category: 'solids',
      },
      {
        name: 'Salt',
        quantity: 2,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Vanilla Extract',
        quantity: 3.5,
        unit: 'g',
        category: 'finishing',
      },
      {
        name: 'Chocolate Chip Cookie Dough',
        quantity: 17,
        unit: '% of final weight',
        preparation: {
          ingredients: [
            {
              name: 'Butter',
              quantity: 100,
              unit: 'g',
            },
            {
              name: 'Brown Sugar',
              quantity: 75,
              unit: 'g',
            },
            {
              name: 'Sugar',
              quantity: 75,
              unit: 'g',
            },
            {
              name: 'Vanilla Extract',
              quantity: 5,
              unit: 'g',
            },
            {
              name: 'Salt',
              quantity: 5,
              unit: 'g',
            },
            {
              name: 'Egg',
              quantity: 1,
              unit: 'large',
            },
            {
              name: 'Flour',
              quantity: 150,
              unit: 'g',
            },
            {
              name: 'Baking Chocolate',
              quantity: 80,
              unit: 'g',
            },
            {
              name: 'Coconut Oil',
              quantity: 20,
              unit: 'g',
            },
          ],
          instructions: [
            'Start by preparing the chocolate, which will involve melting it with coconut oil.',
            'Fill a large pot of water with just a couple inches of water.',
            'Heat the water on the stove until boiling.',
            'Add the chocolate and coconut oil to a metal mixing bowl or double boiler.',
            'Turn off the stove and nest the bowl in the pot - the bottom should not touch the water.',
            'As the steam melts the chocolate and the oil, stir occasionally with a heatproof spatula.',
            'Once the mixture is totally melted and well-integrated, remove from heat.',
            'Line a baking sheet with parchment paper and pour the melted chocolate mixture onto the paper. Let it spread out.',
            'Set aside in the fridge to cool down.',
            'Mix the butter, sugar, brown sugar, vanilla, and salt in a stand mixer, on medium, until smooth.',
            'Add egg and mix until combined.',
            'Pull the chocolate out of the fridge, transfer paper to a cutting board, and cut the chocolate into small pieces.',
            'Add flour to the mixer bowl and mix until combined.',
            'Add the chocolate chips to the mixing bowl while running the mixer on slow. Mix only as long as necessary to integrate. If not entirely cooled, they may streak into the dough, which is cool, but avoid over-mixing.',
            'Transfer dough to a sheet pan and spread out into a thin layer. Store in the freezer from one hour to one day.',
            'Transfer to a cutting board and chop into small bits. Transfer back into the pan, and back into the freezer.',
            "Once it's hard enough not to stick together, transfer to a sealed container or freezer gallon bag.",
            'Store in the freezer until ready to use.',
          ],
          description:
            'This recipe is adapted from "Hello, My Name Is Ice Cream" by Dana Cree, with only a small tweak to make the chocolate chips softer when frozen.',
        },
        category: 'drawing',
      },
    ],
    id: '01952f70-5e3c-7392-ac1f-a38fa78082a5',
    nameKey: 'chocolate-chip-cookie-dough',
    version: 1,
    analysis: {
      totalFat: 144.26,
      milkFat: 140.57999999999998,
      totalSolids: 390.264,
      totalSolidsNonfat: 246.004,
      milkSolidsNonfat: 120.184,
      water: 615.3059999999999,
      sugars: 118,
      totalMass: 1010,
      pod: 111.83749999999999,
      pac: 229.94,
      stabilizers: 1.5,
    },
  },
  {
    name: 'Peanut Butter',
    subtitle: 'Pure peanut butter ice cream',
    description:
      'Creamy peanut butter ice cream that is sweet, nutty, and just the right amount of savory.',
    estimatedMass: 925,
    base: 'Peanut Butter',
    instructions: [
      'Measure out and mix together all of the solids.',
      'Add the peanut butter to a medium-sized mixing bowl.',
      'Add the dairy to a medium-sized, heavy-bottomed pot.',
      'Heat the dairy on the stove until warm, around 90° F.',
      'Slowly add the solids to the pot, whisking as your pour to dissolve the solids. Continue whisking until dissolved.',
      'Add about a 1/4 cup of the warm dairy to the peanut butter, gently whisking to integrate. Repeat this process until thin and runny.',
      'Add the peanut butter mixture back to the pot, scraping the sides with a rubber spatula.',
      'Prepare an ice bath by nesting a metal mixing bowl into a larger bowl that is filled with ice and water.',
      'Temper the egg yolks by whisking them in a bowl, then whisking in about a half cup of warm dairy a little bit at a time.',
      'Add the egg mixture back to the pot, scraping the sides with a rubber spatula.',
      'Continue cooking the mixture, whisking frequently to prevent scrambling the eggs. Cook until the temperature reaches 165° F.',
      'Once the mixture is at temperature, pour through a fine mesh strainer into the bowl in the ice bath.',
      'Whisk occasionally while the mixture cools to below 80° F.',
      'Cover the bowl or transfer the mixture to a container. Store in the fridge to age, at least 4 hours and up to overnight.',
      "Churn in an ice cream machine according to the manufacture's instructions, about 15-20 minutes.",
      'Draw ice cream from the machine and into a freezer-safe container. Store in the freezer.',
    ],
    ingredients: [
      {
        name: 'Whole Milk',
        quantity: 536,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Heavy Cream',
        quantity: 211,
        unit: 'g',
        category: 'dairy',
      },
      {
        name: 'Sugar',
        quantity: 11,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Dextrose',
        quantity: 60,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Fructose',
        quantity: 27,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Milk Powder',
        quantity: 45,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Egg Yolks',
        quantity: 32,
        unit: 'g',
        category: 'other',
      },
      {
        name: 'Stabilizer Blend',
        quantity: 1.5,
        unit: 'g',
        preparation: {
          ingredients: [
            {
              name: 'Locust bean gum',
              quantity: 8,
              unit: 'g',
            },
            {
              name: 'Guar gum',
              quantity: 4,
              unit: 'g',
            },
            {
              name: 'Lambda carageenan',
              quantity: 2,
              unit: 'g',
            },
          ],
          instructions: [
            'Mix together until thoroughly combined.',
            'Store in a sealed container or plastic bag at room temperature.',
          ],
          description:
            'My go-to stabilizer blend, taken from the UnderBelly blog. Makes enough for ~10 batches of ice cream. Can likely be replaced by most commercial stabilizer blends.',
        },
        category: 'solids',
      },
      {
        name: 'Salt',
        quantity: 1.5,
        unit: 'g',
        category: 'solids',
      },
      {
        name: 'Peanut Butter',
        quantity: 75,
        unit: 'g',
        category: 'other',
      },
    ],
    id: '01952f70-5e3c-7392-ac1f-a540b59e581b',
    nameKey: 'peanut-butter',
    version: 1,
    analysis: {
      totalFat: 142.36599999999999,
      milkFat: 95.256,
      totalSolids: 391.24,
      totalSolidsNonfat: 248.87400000000002,
      milkSolidsNonfat: 103.98400000000001,
      water: 606.308,
      sugars: 98,
      totalMass: 1000,
      pod: 111.44669999999999,
      pac: 211.125,
      stabilizers: 1.5,
    },
  },
];

console.log(
  recipes.sort((a, b) => (a.name < b.name ? -1 : 0)).map((r) => r.name),
);
